tap "homebrew/bundle"

# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Command-line fuzzy finder written in Go
brew "fzf"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
